project_id = "wtejjputixebngzshjfj"

[functions.send-team-invite]
verify_jwt = true

[functions.send-gym-invite]
verify_jwt = true

[functions.validate-invite]
verify_jwt = false

[functions.gym-phone-login]
verify_jwt = false

[functions.stripe-create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
